FROM rust:alpine AS builder
LABEL maintainer="kevin-rs <https://github.com/kevin-rs>"
LABEL author="Mahmoud Harmouch <https://github.com/wiseaidev>"
RUN apk update && apk upgrade
RUN apk add --no-cache \
    build-base \
    pkgconfig \
    openssl-dev \
    openssl-libs-static \
    git

WORKDIR /kevin
COPY Cargo.toml Cargo.lock INSTALLATION.md ./
COPY auto-derive ./auto-derive
COPY autogpt ./autogpt
COPY auto-net ./auto-net
COPY iac-rs ./iac-rs
COPY README.md ./

RUN cargo vendor vendor

RUN mkdir -p .cargo && \
    printf '[source.crates-io]\nreplace-with = "vendored-sources"\n[source.vendored-sources]\ndirectory = "vendor"\n' > .cargo/config.toml

RUN cargo build --release --offline --all-features -p autogpt

FROM alpine:3.21
RUN addgroup -S kevin && \
    adduser -S -G kevin kevin

RUN apk add --no-cache sudo

RUN addgroup -S sudo && \
    addgroup kevin sudo && \
    echo "%sudo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/kevin

COPY certs/ ./certs
RUN chown -R kevin:kevin ./certs

COPY --from=builder /kevin/target/release/orchgpt /usr/local/bin/orchgpt

USER kevin

ENTRYPOINT [ "/usr/local/bin/orchgpt" ]
