[package]
name = "designer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
autogpt = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
