name: 🧹 Cargo Clippy Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-clippy:
    name: 🔍 Run Clippy Linter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        features:
          [
            "",
            "cli",
            "img",
            "git",
            "gem",
            "xai",
            "net",
            "mail",
            "oai",
            "mem",
            "cld",
            "gpt",
            "co",
            "hf",
            "mta",
            "mcp",
            "mta,cli",
            "mta,gpt",
            "gpt,cli",
            "cli,mcp",
            "hf,mcp",
            "oai,mcp",
            "hf,net",
            "cli,hf",
            "cli,gem",
            "cli,oai",
            "cli,cld",
            "cli,xai",
            "cli,co",
            "cli,hf,net",
            "cli,gem,oai",
            "cli,gem,gpt,net,git",
            "gem,gpt",
            "oai,gpt",
            "cld,gpt",
            "co,gpt",
            "xai,gpt",
            "hf,gpt",
            "all-features",
          ]
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v7

      - name: 🧪 Run Clippy
        run: |
          if [ "${{ matrix.features }}" == "all-features" ]; then
            cargo clippy --all-features -- -D warnings
          elif [ -z "${{ matrix.features }}" ]; then
            cargo clippy --no-default-features -- -D warnings
          else
            cargo clippy --no-default-features --features "${{ matrix.features }}" -- -D warnings
          fi
